version: '2.3'
services:
    worker:
        scale: 4
        build:
            context: .
            dockerfile: Dockerfile.worker
        image: worker:latest
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./scratch:/tmp/scratch
            - ${KALE_SRC}:/opt/kale
        cpus: 0.2
        mem_limit: 500m
        memswap_limit: 1000m
        ulimits:
            memlock: -1
    kale_manager:
        build:
            context: .
            dockerfile: Dockerfile.manager
        image: manager:latest
        volumes:
            - ${KALE_SRC}:/opt/kale
        hostname: kale_manager
        depends_on:
            - "worker"
    slurm:
        build:
            context: .
            dockerfile: Dockerfile.slurm
        image: slurm:latest
        hostname: slurm 
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
        depends_on:
            - "worker"
    torque:
        build: 
            context: .
            dockerfile: Dockerfile.torque
        image: torque:latest
        hostname: torque 
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./scratch:/tmp/scratch
        depends_on:
            - "worker"
    fireworks:
        build:
            context: .
            dockerfile: Dockerfile.fireworks
        image: fireworks:latest
        hostname: fireworks
#        ports:
#            - "55000:5000"
        depends_on:
            - "worker"
            - "mongodb"
    mongodb:
        image: mongo
        hostname: mongodb
        expose:
            - "27017"
        ports:
            - "27017:27017"
    jupyter:
        build:
            context: .
            dockerfile: Dockerfile.jupyter
        image: jupyter:latest
        hostname: jupyter
        volumes:
            - ./scratch:/tmp/scratch
            - ./notebooks:/home/jovyan/work
            - ${KALE_SRC}:/opt/kale
        ports:
            - "18888:8888"
        depends_on:
            - "worker"
